import { AppDefinition } from '../types';

export const SYSTEM_APPS: AppDefinition[] = [
  {
    id: 'explorer',
    name: 'File Explorer',
    nameAr: 'مستكشف الملفات',
    icon: 'folder',
    iconType: 'Ionicons',
    iconColor: '#F2C811',
    bgColor: '#1E1E1E',
    pinnedToTaskbar: true,
    desktopShortcut: true,
    category: 'system',
  },
  {
    id: 'edge',
    name: 'Microsoft Edge',
    nameAr: 'Microsoft Edge',
    icon: 'compass-outline',
    iconType: 'Ionicons',
    iconColor: '#0078D4',
    bgColor: '#0078D4',
    pinnedToTaskbar: true,
    desktopShortcut: true,
    category: 'productivity',
  },
  {
    id: 'store',
    name: 'Microsoft Store',
    nameAr: 'متجر Microsoft',
    icon: 'bag-handle-outline',
    iconType: 'Ionicons',
    iconColor: '#0078D4',
    bgColor: '#0078D4',
    pinnedToTaskbar: true,
    desktopShortcut: true,
    category: 'system',
  },
  {
    id: 'settings',
    name: 'Settings',
    nameAr: 'الإعدادات',
    icon: 'settings-outline',
    iconType: 'Ionicons',
    iconColor: '#9E9E9E',
    bgColor: '#2E2E2E',
    pinnedToTaskbar: true,
    desktopShortcut: true,
    category: 'system',
  },
  {
    id: 'calculator',
    name: 'Calculator',
    nameAr: 'الحاسبة',
    icon: 'calculator-outline',
    iconType: 'Ionicons',
    iconColor: '#00A4EF',
    bgColor: '#0078D4',
    pinnedToTaskbar: false,
    desktopShortcut: true,
    category: 'utilities',
  },
  {
    id: 'notepad',
    name: 'Notepad',
    nameAr: 'المفكرة',
    icon: 'document-text-outline',
    iconType: 'Ionicons',
    iconColor: '#4CAF50',
    bgColor: '#107C41',
    pinnedToTaskbar: false,
    desktopShortcut: true,
    category: 'productivity',
  },
  {
    id: 'terminal',
    name: 'Terminal',
    nameAr: 'موجه الأوامر',
    icon: 'terminal-outline',
    iconType: 'Ionicons',
    iconColor: '#000000',
    bgColor: '#222222',
    pinnedToTaskbar: false,
    desktopShortcut: true,
    category: 'utilities',
  },
  {
    id: 'games',
    name: 'Games Hub',
    nameAr: 'مركز الألعاب',
    icon: 'game-controller-outline',
    iconType: 'Ionicons',
    iconColor: '#107C41',
    bgColor: '#107C41',
    pinnedToTaskbar: false,
    desktopShortcut: true,
    category: 'entertainment',
  },
  {
    id: 'photos',
    name: 'Photos',
    nameAr: 'الصور',
    icon: 'images-outline',
    iconType: 'Ionicons',
    iconColor: '#008272',
    bgColor: '#008272',
    pinnedToTaskbar: false,
    desktopShortcut: true,
    category: 'entertainment',
  },
  {
    id: 'mediaplayer',
    name: 'Media Player',
    nameAr: 'مشغل الوسائط',
    icon: 'play-circle-outline',
    iconType: 'Ionicons',
    iconColor: '#E3008C',
    bgColor: '#E3008C',
    pinnedToTaskbar: false,
    desktopShortcut: true,
    category: 'entertainment',
  },
  {
    id: 'stickynotes',
    name: 'Sticky Notes',
    nameAr: 'الملاحظات الملصقة',
    icon: 'copy-outline',
    iconType: 'Ionicons',
    iconColor: '#FFB900',
    bgColor: '#FFB900',
    pinnedToTaskbar: false,
    desktopShortcut: true,
    category: 'productivity',
  },
  {
    id: 'recyclebin',
    name: 'Recycle Bin',
    nameAr: 'سلة المحذوفات',
    icon: 'trash-outline',
    iconType: 'Ionicons',
    iconColor: '#707070',
    bgColor: '#333333',
    pinnedToTaskbar: false,
    desktopShortcut: true,
    category: 'system',
  },
];
